{{- include "_helpers.tpl" . }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-app-chart.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "my-app-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "my-app-chart.name" . }}
    spec:
      containers:
      - name: my-app-container
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets.name }}
